// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comparison =
  | { type: "gt"; value: number }
  | { type: "lt"; value: number };
