// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatisticFilter } from "./StatisticFilter";
import type { TextQuery } from "./TextQuery";

export type Filter =
  | ({ type: "numerical" } & StatisticFilter)
  | ({ type: "textual" } & TextQuery);
