// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comparison } from "./Comparison";
import type { Statistic } from "./Statistic";

export type Filter = { statistic: Statistic, comparison: Comparison, };
