/* eslint-disable */
// @ts-nocheck
/*    @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@    */

import type { NameHistoryData } from "./NameHistoryData.ts";
import type { GetNameHistoryRequest } from "./GetNameHistoryRequest.ts";
import type { Query } from "@qubit-rs/client";
import type { NameData } from "./NameData.ts";
import type { SearchNamesResponse } from "./SearchNamesResponse.ts";
import type { Filter } from "./Filter.ts";
import type { TextQuery } from "./TextQuery.ts";
import type { Statistic } from "./Statistic.ts";
import type { SearchNamesRequest } from "./SearchNamesRequest.ts";

export type { NameHistoryData } from "./NameHistoryData.ts";
export type { GetNameHistoryRequest } from "./GetNameHistoryRequest.ts";
export type { Query } from "@qubit-rs/client";
export type { NameData } from "./NameData.ts";
export type { SearchNamesResponse } from "./SearchNamesResponse.ts";
export type { Filter } from "./Filter.ts";
export type { TextQuery } from "./TextQuery.ts";
export type { Statistic } from "./Statistic.ts";
export type { SearchNamesRequest } from "./SearchNamesRequest.ts";

export type QubitServer = { get_name_history: Query<[request: GetNameHistoryRequest, ], { Ok : NameHistoryData } | { Err : string }>, search_names: Query<[request: SearchNamesRequest, ], { Ok : SearchNamesResponse } | { Err : string }> };