// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderSelection } from "./GenderSelection";

export type Measurement = { "Popularity": GenderSelection } | { "DenseRank": GenderSelection } | { "Count": GenderSelection } | "Masculinity" | "Femininity" | "GenderNeutrality";
