// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderSelection } from "./GenderSelection";

export type Measurement =
  | { type: "popularity"; genderSelection: GenderSelection }
  | { type: "denseRank"; genderSelection: GenderSelection }
  | { type: "count"; genderSelection: GenderSelection }
  | { type: "masculinity" }
  | { type: "femininity" }
  | { type: "genderNeutrality" };
