// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderSelection } from "./GenderSelection";

export type Measurement = { "popularity": GenderSelection } | { "denseRank": GenderSelection } | { "count": GenderSelection } | "masculinity" | "femininity" | "genderNeutrality";
