// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NameHistoryData = {
  countBoth: Array<bigint>;
  countF: Array<bigint>;
  countM: Array<bigint>;
  denseRankBoth: Array<bigint>;
  denseRankF: Array<bigint>;
  denseRankM: Array<bigint>;
  popularityBoth: Array<number>;
  popularityF: Array<number>;
  popularityM: Array<number>;
};
