// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NameHistoryData = { count_both: Array<bigint>, count_f: Array<bigint>, count_m: Array<bigint>, dense_rank_both: Array<bigint>, dense_rank_f: Array<bigint>, dense_rank_m: Array<bigint>, popularity_both: Array<number>, popularity_f: Array<number>, popularity_m: Array<number>, };
