// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generation } from "./Generation";

export type Range =
  | { type: "generation"; generation: Generation }
  | { type: "previous"; previous: number }
  | { type: "between"; min: number; max: number }
  | { type: "allLivingPeople" }
  | { type: "allYears" };
