// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generation } from "./Generation";

export type Range =
  | { generation: Generation }
  | { previous: number }
  | { between: [number, number] }
  | "allLivingPeople"
  | "allYears";
