// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";
import type { Statistic } from "./Statistic";
import type { TextQuery } from "./TextQuery";

export type SearchNamesRequest = { text_query: TextQuery | null, filters: Array<Filter>, sort: Statistic | null, };
