// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";
import type { Sort } from "./Sort";

export type SearchNamesRequest = { filters: Array<Filter>; sort: Sort | null };
