// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregateFunction } from "./AggregateFunction";
import type { Range } from "./Range";

export type Selection =
  | { type: "oneYear"; year: number }
  | { type: "manyYears"; aggregateFunction: AggregateFunction; range: Range };
