// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregateFunction } from "./AggregateFunction";
import type { Range } from "./Range";

export type Selection = { "OneYear": number } | { "ManyYears": { aggregate_function: AggregateFunction, range: Range, } };
