// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";
import type { Statistic } from "./Statistic";

export type Sort = { statistic: Statistic; direction: SortDirection };
