// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Measurement } from "./Measurement";
import type { Selection } from "./Selection";

export type Statistic = { measurement: Measurement, selection: Selection, };
