// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMethod } from "./SearchMethod";

export type TextQuery = { query: string; method: SearchMethod };
