/* eslint-disable */
// @ts-nocheck
/*    @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@    */

import type { NameHistoryData } from "./NameHistoryData.ts";
import type { GetNameHistoryRequest } from "./GetNameHistoryRequest.ts";
import type { Query } from "@qubit-rs/client";

export type { NameHistoryData } from "./NameHistoryData.ts";
export type { GetNameHistoryRequest } from "./GetNameHistoryRequest.ts";
export type { Query } from "@qubit-rs/client";

export type QubitServer = { get_name_history: Query<[request: GetNameHistoryRequest, ], { Ok : NameHistoryData } | { Err : string }> };